добавляет функции генерации чисел
htmlacademy-javascript/235940-keksobooking-24 pull request #2
Opened 2021-09-24 22:43 UTC by artsamoilov

2021-09-25 00:25 UTC, artsamoilov commented
Сейчас понял, что в первой функции вместо проверки начального и конечного значений можно было использовать `Math.min()` и `Math.max()` с обоими аргументами, и таким образом вообще обойтись без тернарного оператора. Поправлю это завтра, надеюсь успею до проверки.

Есть ещё небольшой вопрос по ТЗ: по нему передаваемые в функции аргументы не могут быть отрицательными, но надо ли это проверять? Хотел использовать в расчётах абсолютные значения `min` и `max`, но пока убрал, так как эта фраза в ТЗ показалась немного двусмысленной.

2021-09-25 13:46 UTC, dtsaryov requested changes
> В первой функции вместо проверки начального и конечного значений можно было ещё использовать Math.min() и Math.max() с обоими аргументами, и таким образом вообще обойтись без тернарного оператора. Но тогда скорее всего придётся ввести ещё 2 переменные, это дополнительные 2 строчки кода, но вроде воспринимается чуть попроще. Как лучше поступить в таком случае?

Не заморачивайся и оставь как есть.

В крайнем случае, можно проверить, что если min > max, и бросить ошибку

> Есть ещё небольшой вопрос по ТЗ: по нему передаваемые в функции аргументы не могут быть отрицательными, но надо ли это проверять? Хотел использовать в расчётах абсолютные значения min и max, но пока убрал, так как эта фраза в ТЗ показалась немного двусмысленной.

Аналогично с предыдущим вопросом

2021-09-25 13:46 UTC, dtsaryov commented on js/main.js
> +function getFloatFromRange(min, max) {
Давай для удобства сразу начнем использовать синтаксис стрелочных функций

2021-09-25 13:46 UTC, dtsaryov commented on js/main.js
> +function getFormattedFloatFromRange(min, max, floatLength) {
Можно обойтись 2мя функциями, просто добавив аргумент precision (точность, твой floatLength) для getFloatFromRange

2021-09-25 13:46 UTC, dtsaryov commented on js/main.js
> +  return getFloatFromRange(min, max).toFixed(floatLength);
Обращаю твое внимание на то, что toFixed возвращает строку, а не число

2021-09-25 14:31 UTC, artsamoilov commented on js/main.js
> +  return getFloatFromRange(min, max).toFixed(floatLength);
Вот это я не знал... А будет ок просто обернуть возвращаемое значение в `Number()`?

2021-09-25 14:38 UTC, artsamoilov commented on js/main.js
> +function getFormattedFloatFromRange(min, max, floatLength) {
Получается, можно практически всё перенести в getFloatFromRange, а внутри getIntegerFromRange вызывать первую функцию с precision = 0? Тогда наверное и `Math.floor()` будет не нужен

2021-09-25 14:56 UTC, artsamoilov commented
> В крайнем случае, можно проверить, что если min > max, и бросить ошибку

У меня сейчас если min > max, то они меняются местами

2021-09-27 07:40 UTC, dtsaryov approved these changes

2021-09-27 07:40 UTC, merged