Module7 task1
htmlacademy-javascript/235940-keksobooking-24 pull request #5
Opened 2021-10-14 23:06 UTC by artsamoilov

2021-10-16 13:43 UTC, dtsaryov requested changes

2021-10-16 13:43 UTC, dtsaryov commented on js/main.js
> +import {createPopup} from './utils/card.js';
Давай так и назовем модуль - popup

2021-10-16 13:43 UTC, dtsaryov commented on js/main.js
> +createPopup(housingOffers[getIntegerFromRange(0, HOUSING_QUANTITY - 1)]);
достаточно было просто взять первый элемент )

2021-10-16 13:43 UTC, dtsaryov commented on js/utils/data.js
> +const HOUSING_TYPES = {
Это перечисление

Б8. Название классов, конструкторов и перечислений начинается с заглавной буквы. В названии используются английские существительные. Значения перечислений объявлены как константы.

2021-10-16 13:43 UTC, dtsaryov commented on js/utils/card.js
> +  const photoTemplate = popupPhotosContainer.querySelector('.popup__photo');
Старайся объявлять переменные непосредственно перед использованием, а не за "километр"

2021-10-16 13:43 UTC, dtsaryov commented on js/utils/card.js
> +  const addExistingSource = (node, source) => source ? node.src = source : node.classList.add('hidden');
Вынеси наружу - внутренние функции усложняют чтение и понимание кода

2021-10-16 13:43 UTC, dtsaryov commented on js/utils/card.js
> +const createPopup = (housing) => {
Попробуй применить деструктурирование, чтобы внутри функции не писать qwe.asd.zxc

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2021-10-16 16:12 UTC, artsamoilov commented on js/utils/data.js
> +const HOUSING_TYPES = {
Проверил критерий, а это не будет считаться словарём? В чём вообще отличие словаря от перечисления? Это как-то не очевидно..

2021-10-16 16:17 UTC, artsamoilov commented on js/utils/card.js
> +const createPopup = (housing) => {
Насколько имеет смысл деструктурировать объект? Будет ли ок передать `{author, offer}` или лучше углубиться до `{{avatar},{title, address, price, type ...}}`?

2021-10-16 20:57 UTC, dtsaryov commented on js/utils/card.js
> +const createPopup = (housing) => {
попробуй и посмотри, как будет лучше

2021-10-16 20:57 UTC, dtsaryov commented on js/utils/data.js
> +const HOUSING_TYPES = {
Не будет.

Перечисление - неизменяемая структура данных, в отличие от словаря

2021-10-16 22:45 UTC, artsamoilov commented on js/utils/card.js
> +const createPopup = (housing) => {
сделал второй вариант.. с одной стороны появилась конская строка параметров, но с другой стороны весь код ниже стал более удобным для восприятия.. кажется, это меньшее из двух зол)

2021-10-17 11:23 UTC, dtsaryov approved these changes

2021-10-17 11:23 UTC, dtsaryov commented on js/utils/popup.js
> +  document.querySelector('#map-canvas').append(cardTemplate);
Недоглядел - нужно сделать модуль map, в котором будет этот вызов.

Функция createPopup должна только создавать элемент и возвращать его

2021-10-17 11:23 UTC, merged