Надо подкачаться
htmlacademy-javascript/235940-keksobooking-24 pull request #9
Opened 2021-10-27 22:44 UTC by artsamoilov

---
:mortar_board: [Надо подкачаться](https://up.htmlacademy.ru/javascript/24/user/235940/tasks/19)

2021-10-30 00:10 UTC, artsamoilov commented on js/utils/modal.js
> +const showSuccessModal = () => {
кажется, здесь потерялись скобки? это ведь должна быть функция?

2021-10-30 00:14 UTC, artsamoilov commented on js/utils/form.js
> +        onSuccess();
ты имеешь в виду вместо `onSuccess` вызывать тут `showSuccessNotification`? но она же колбэком как раз передаётся (из `main.js`)

2021-10-30 00:14 UTC, artsamoilov commented
Сорри, пришлось с `push --force` отправить: зашёл в тупик, откатился до последнего локального коммита, с него запушил изменения, перешёл в рабочую ветку, и после этого гит отказывался пушить по-хорошему. Надеюсь ничего не сломал(

2021-11-01 15:05 UTC, dtsaryov requested changes

2021-11-01 15:05 UTC, dtsaryov commented on js/utils/form.js
> +const resetPrice = () => {
Некорректное имя функции - мы ведь здесь просто обновляем два аттрибута, а не значение поля.

Лучшее будет назвать просто `setPriceConstraint`.

Ну и правильнее будет передавать текущий тип через аргументы этой функции

2021-11-01 15:05 UTC, dtsaryov commented on js/utils/form.js
> +const resetPage = () => {
Эту функцию будет правильнее расположить в main

2021-11-01 15:05 UTC, dtsaryov commented on js/utils/form.js
> +  resetMap();
Ну и это не очень правильно, что из формы мы влияем на карту почему-то

2021-11-01 15:05 UTC, dtsaryov commented on js/utils/form.js
> +        onSuccess();
Сейчас у тебя несколько смешанные связи между модулями.

В моем представлении правильнее всего, когда main является связующим звеном между функциональными модулями (form, map), но при это вызывать утилитные функции внутри этих модулей напрямую более правильно, чем прокидывать эти коллбэки из main

2021-11-02 12:22 UTC, dtsaryov approved these changes

2021-11-02 12:22 UTC, dtsaryov commented on js/utils/notification.js
> +function hideNotification () {
Д5. Все функции объявлены единообразно.

2021-11-02 12:22 UTC, merged